package org.itrunner.wechat;

import java.util.Base64;

public class Test {
    public static void main(String[] args) throws Exception {
       System.out.println(new String(Base64.getDecoder().decode("eyJqdGkiOiJhMDIzYTJhNS0zNDQwLTQ1NTktOGVhMC0yNzMyN2NkYzBmZGIiLCJleHAiOjE1NzQ0NDE1NzQsIm5iZiI6MCwiaWF0IjoxNTc0NDIzNTc0LCJpc3MiOiJodHRwczovL3Nzby5pYXRhLWFzZC5vcmcvYXV0aC9yZWFsbXMvcGFzcyIsInN1YiI6IjBmOTQyYTA3LTQyMDMtNDczOS05YjI3LWY1ODVkMDQ0YmJiYSIsInR5cCI6IkJlYXJlciIsImF6cCI6InNlY3VyaXR5LWFkbWluLWNvbnNvbGUiLCJub25jZSI6IjI5YWI0NGU5LWQ4YjItNGYyMy04ZjEzLWE2MGI1MmJiMjUzZSIsImF1dGhfdGltZSI6MTU3NDQyMzU3Mywic2Vzc2lvbl9zdGF0ZSI6IjM5MDhmZTZiLTdlZTAtNGVhNC05NjljLTBlNzg3ZGY1YmZjZiIsImFjciI6IjEiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiSmFzb24gU3VuIiwicHJlZmVycmVkX3VzZXJuYW1lIjoic3VuamMiLCJnaXZlbl9uYW1lIjoiSmFzb24iLCJmYW1pbHlfbmFtZSI6IlN1biIsImVtYWlsIjoic2pjLTkyNUAxNjMuY29tIn0")));
    }
}
